let g:coc_global_extensions = [
  \ 'coc-css',
  \ 'coc-docker',
  \ 'coc-esbonio',
  \ 'coc-explorer',
  \ 'coc-go',
  \ 'coc-html',
  \ 'coc-json',
  \ 'coc-markdownlint',
  \ 'coc-pyright',
  \ 'coc-rust-analyzer',
  \ 'coc-sh',
  \ 'coc-snippets',
  \ 'coc-texlab',
  \ 'coc-tsserver',
  \ 'coc-yaml',
  \ ]
