language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"

before_script:
  - mkdir -p ~/dotfiles-install-dir

script:
  - HOME=~/dotfiles-install-dir ./install
