name: Test

on:
  - push
  - pull_request

jobs:
  test-code:
    name: Test code
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version:
        - '2.7'
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - 'pypy-2.7'
        - 'pypy-3.8'

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Installation Script
        run: |
          mkdir -p ~/dotfiles-install-dir
          HOME=~/dotfiles-install-dir ./install

      - name: Test Bash Configuration files
        run: |
          bash --version
          INPUTRC=bash/inputrc source bash/bashrc

      - name: Test Git Configuration files
        run: |
          git --version
          git config --file=git/gitconfig -l

      - name: Test Vim Configuration files
        run: |
          vim --version
          vim -c 'so vim/vimrc' -c ':q!'
